### ISSUE TITLE
Error with the descriptive table 

### ISSUE THREAD

**Issue by sebastiz** [jinseob2kim/jsmodule#1]
I have been using jsmodule. I have run the example code from tb1moduleUI from the vignette but I keep getting "Warning: Error in [: invalid subscript type 'list'". I run the code exactly as it is in the example:

```
library(shiny);library(DT);library(data.table);library(jstable)
ui <- fluidPage(
sidebarLayout(
sidebarPanel(
tb1moduleUI("tb1")
),
mainPanel(
DTOutput("table1")
)
)
)
server <- function(input, output, session) {
data <- reactive(mtcars)
data.label <- reactive(jstable::mk.lev(mtcars))
out_tb1 <- callModule(tb1module2, "tb1", data = data, data_label = data.label,
data_varStruct = NULL)
output$table1 <- renderDT({
tb <- out_tb1()$table
cap <- out_tb1()$caption
out.tb1 <- datatable(tb, rownames = T, extension= "Buttons", caption = cap)
return(out.tb1)
})
}
```

I think this is coming from the line: tb <- out_tb1()$table

Can you tell me what is wrong?

**Comment by jinseob2kim** [comment]
I find a bug and fix now : data.frame vs data.table issues 

Please reinstall latest version via remotes::install_github("jinseob2kim/jsmodule")

**Comment by sebastiz** [comment]
Ok great.

Thanks!
________________________________
