### ISSUE TITLE
non-zero exit status

### ISSUE THREAD

**Issue by zgwjohn** [jinseob2kim/jsmodule#3]
Hi, I've encountered the following issue and was unable to install the package:

* installing *source* package 'jsmodule' ...
** package 'jsmodule' successfully unpacked and MD5 sums checked
** using staged installation
** R
** inst
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  namespace 'ellipsis' 0.3.1 is already loaded, but >= 0.3.2 is required
Calls: <Anonymous> ... asNamespace -> loadNamespace -> namespaceImport -> loadNamespace
Execution halted
ERROR: lazy loading failed for package 'jsmodule'
* removing 'F:/Documents/R/win-library/4.0/jsmodule'
Warning in install.packages :
  installation of package ‘E:/Downloads/jsmodule_1.3.0.tar.gz’ had non-zero exit status

**Comment by jinseob2kim** [comment]
Sorry I'm late. Could you install ellipsis >=0.3.2 version?
